apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pinpoint-batch.fullname" . }}
  labels:
{{ include "pinpoint-batch.labels" . | indent 4 }}
type: Opaque
data:
  SPRING_DATASOURCE_HIKARI_JDBC-URL: {{ include "pinpoint-batch.mysql.full-url" . | b64enc | quote }}
  SPRING_DATASOURCE_HIKARI_USERNAME: {{ include "pinpoint-batch.mysql.username" . | b64enc | quote }}
  SPRING_DATASOURCE_HIKARI_PASSWORD: {{ include "pinpoint-batch.mysql.password" . | b64enc | quote }}
  SPRING_META-DATASOURCE_HIKARI_JDBC-URL: {{ include "pinpoint-batch.mysql.full-metaurl" . | b64enc | quote }}
  SPRING_META-DATASOURCE_HIKARI_USERNAME: {{ include "pinpoint-batch.mysql.username" . | b64enc | quote }}
  SPRING_META-DATASOURCE_HIKARI_PASSWORD: {{ include "pinpoint-batch.mysql.password" . | b64enc | quote }}
  mysql-root-password: {{ include "pinpoint-batch.mysql.password" . | b64enc | quote }}
  mysql-password: {{ include "pinpoint-batch.mysql.password" . | b64enc | quote }}
  ALARM_MAIL_SERVER_USERNAME: {{ .Values.mail.server.username | b64enc | quote }}
  ALARM_MAIL_SERVER_PASSWORD: {{ .Values.mail.server.password | b64enc | quote }}