apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pinpoint-web.fullname" . }}
  labels:
{{ include "pinpoint-web.labels" . | indent 4 }}
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.profiles }}"
  SERVER_PORT: "{{ .Values.serverPort }}"
  PINPOINT_ZOOKEEPER_ADDRESS: "{{ include "pinpoint-web.zookeeper.address" . }}"
  CONFIG_SENDUSAGE: "{{ .Values.sendUsage }}"
  JDBC_DRIVERCLASSNAME: "com.mysql.jdbc.Driver"
  JDBC_URL: "{{ include "pinpoint-web.mysql.full-url" .}}"