apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pinpoint-web.fullname" . }}
  labels:
{{ include "pinpoint-web.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "pinpoint-web.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "pinpoint-web.labels" . | indent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      initContainers:
       - name: wait-mysql
         image: alpine
         command:
           - sh
           - -c
           - >-
             for i in $(seq 1 300); do nc -zvw1 {{ include "pinpoint-web.mysql.url" . }} {{ include "pinpoint-web.mysql.port" . }} && exit 0 || sleep 3; done; exit 1
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: ui
              containerPort: {{ .Values.serverPort }}
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ template "pinpoint-web.fullname" . }}
          - secretRef:
              name: {{ template "pinpoint-web.fullname" . }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
