apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinpoint-collector.fullname" . }}
  labels:
{{ include "pinpoint-collector.labels" . | indent 4 }}
data:
  PINPOINT_ZOOKEEPER_ADDRESS: "{{ include "pinpoint-collector.zookeeper.address" . }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.profiles }}"
